# Add to the coin.py module created in the previous challenges, a function
# called resume() that shows on the screen some information generated by the
# functions we already have in the module created so far.

from coin import resume

price = float(input("Enter a price: R$"))
increase = int(input("Increase: ")) / 100
decrease = int(input("Decrease: ")) / 100
resume(price, increase, decrease)
